services:
  - type: web
    name: ShizuMusicBot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: API_HASH
        sync: false
      - key: API_ID
        sync: false
      - key: STRING_SESSION
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: MONGO_DB_URL
        sync: false
      - key: UPDATES_CHANNEL
        sync: false
      - key: SUPPORT_GROUP
        sync: false



